spring:
  datasource:
    url: jdbc:mysql://localhost/helpdesk
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      sort-parameter: ordem
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
  flyway:
    enabled: true
    repair-on-migrate: true
    locations: classpath:db/migration