CREATE TABLE TB_CLIENT(

    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_DATE DATE NOT NULL,

    PRIMARY KEY(ID),
    CONSTRAINT fk_client_profile FOREIGN KEY (id) REFERENCES TB_PEOPLE (id) ON DELETE CASCADE ON UPDATE CASCADE

);