CREATE TABLE TB_PROFILES (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    people_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,

    CONSTRAINT fk_profiles_people FOREIGN KEY (people_id) REFERENCES TB_PEOPLE (id) ON DELETE CASCADE ON UPDATE CASCADE
);