CREATE TABLE TB_REQUEST (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OPENING_DATE DATE NOT NULL,
    CLOSING_DATE DATE,
    PRIORITY VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    OBSERVATION VARCHAR(255),
    technician_id BIGINT,
    client_id BIGINT,

    CONSTRAINT fk_request_technician FOREIGN KEY (technician_id) REFERENCES TB_TECHNICIAN (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_request_client FOREIGN KEY (client_id) REFERENCES TB_CLIENT (id) ON DELETE SET NULL ON UPDATE CASCADE
);